import test from 'node:test';
import assert from 'node:assert/strict';
import {hex,uuid,validUUID,parseText,parseBtsnoop,byteDiff,validateCommand,sampleSession} from '../dist/core.mjs';
test('strict bytes and UUID normalization',()=>{assert.equal(hex('0x01:0A ff'),'01 0A FF');assert.equal(hex([0,255]),'00 FF');assert.throws(()=>hex('01 garbage'));assert.throws(()=>hex('F'));assert.throws(()=>hex([256]));assert.ok(validUUID(uuid('fff0')));assert.ok(!validUUID('handle0025'));});
test('line logs preserve complete spaced payloads and response mode',()=>{const r=parseText('[0.0] WRITE_CMD action="Power on" service=fff0 char=fff1 value=01 0A FF\n[0.1] NOTIFY action="Power on" service=fff0 char=fff2 value=B0 0A');assert.equal(r.observations[0].value,'01 0A FF');assert.equal(r.observations[0].response,false);assert.equal(r.observations[1].value,'B0 0A');});
test('quoted CSV and malformed rows',()=>{const r=parseText('direction,action,characteristic,value,response\nwrite,"Power, on",fff1,01 00,true');assert.equal(r.observations[0].action,'Power, on');assert.equal(r.observations[0].response,true);assert.throws(()=>parseText('direction,value\nwrite,01,extra'));assert.throws(()=>parseText('[{broken]'));assert.throws(()=>parseText('WRITE value=0G'));});
test('JSON retains zero bytes, unknown mode and unresolved handles',()=>{const r=parseText(JSON.stringify([{direction:'write',value:[0],handle:'0x0025'}]));assert.equal(r.observations[0].value,'00');assert.equal(r.observations[0].characteristic,'');assert.equal(r.observations[0].response,null);});
test('diff detects substitutions and insertion',()=>{const d=byteDiff('01 02','01 03 04');assert.deepEqual(d.map(x=>x.changed),[false,true,true]);});
test('synthetic or unreviewed commands cannot become eligible',()=>{const s=sampleSession(),c={...s.observations[0],stage:'tested',notes:'test',name:'On'};assert.ok(validateCommand(c,s).length);c.synthetic=false;s.synthetic=false;assert.equal(validateCommand(c,s).length,0);c.response=null;assert.ok(validateCommand(c,s).length);});
function snoop(packets){const parts=packets.map(p=>{const r=Buffer.alloc(24+p.length);r.writeUInt32BE(p.length,0);r.writeUInt32BE(p.length,4);r.writeBigUInt64BE(1000000n,16);Buffer.from(p).copy(r,24);return r;});const head=Buffer.alloc(16);head.write('btsnoop\0');head.writeUInt32BE(1,8);head.writeUInt32BE(1002,12);const b=Buffer.concat([head,...parts]);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);}
test('btsnoop H4 writes and notifications retain handle and do not invent UUIDs',()=>{const r=parseBtsnoop(snoop([[2,1,32,9,0,5,0,4,0,0x52,0x25,0,1,2],[2,1,32,8,0,4,0,4,0,0x1b,0x26,0,7]]));assert.equal(r.observations.length,2);assert.equal(r.observations[0].value,'01 02');assert.equal(r.observations[0].handle,'0x0025');assert.equal(r.observations[0].characteristic,'');assert.equal(r.observations[1].direction,'notify');});
test('fragmented ACL packets are reassembled per connection',()=>{const r=parseBtsnoop(snoop([[2,1,32,6,0,5,0,4,0,0x12,0x25],[2,1,16,3,0,0,1,2]]));assert.equal(r.observations[0].value,'01 02');assert.equal(r.observations[0].response,true);});
test('truncated capture rejects entire import',()=>{const b=snoop([[2,1,32,9,0,5,0,4,0,0x52,0x25,0,1,2]]);assert.throws(()=>parseBtsnoop(b.slice(0,b.byteLength-1)));});
