package dev.nphil.blestudio.crypto

import dev.nphil.blestudio.model.AttOperation
import dev.nphil.blestudio.model.BleEvent
import dev.nphil.blestudio.model.CaptureSession
import dev.nphil.blestudio.model.DeviceIdentity
import dev.nphil.blestudio.model.EventDirection
import dev.nphil.blestudio.model.EventSource
import dev.nphil.blestudio.model.hexToBytes
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The Xiaomi MiBeacon v4/v5 preset against the public vector documented for `ble_monitor`.
 *
 * Service data `58598D0A17…`, bindkey `FDD8CE9C…`, MIC `790DF258`, plaintext `0F0003000000`; see
 * https://home-is-where-you-hang-your-hack.github.io/ble_monitor/MiBeacon_protocol. The layout
 * itself is `Bluetooth-Devices/xiaomi-ble` `_decrypt_mibeacon_v4_v5`. Nothing in this test is
 * generated by the app, so it fails if the preset's nonce, AAD, tag length or ranges drift.
 */
class MiBeaconPresetTest {

    private val serviceData = "58598D0A170FC4E044EF547CC27A5C03A1000000790DF258"
    private val bindkey = "FDD8CE9C08AE7533A79BDAF0BB755E96"
    private val address = "54:EF:44:E0:C4:0F"
    private val plaintext = "0F0003000000"

    @Test
    fun `the mac-in-frame preset decrypts the public vector`() {
        val scheme = Presets.xiaomiMiBeaconV4V5.template.copy(keyHex = bindkey)
        val result = CipherEngine.decrypt(scheme, serviceData.hexToBytes(), FrameContext())
        assertEquals("nonce", "0FC4E044EF548D0A17000000", result.nonceHex)
        assertEquals("aad", "11", result.aadHex)
        assertEquals("ciphertext", "7CC27A5C03A1", result.ciphertextHex)
        assertEquals("plaintext", plaintext, result.plaintextHex)
        assertEquals(true, result.verified)
        assertNull(result.error)
    }

    /** The variant that takes the address from the session must reach the same nonce. */
    @Test
    fun `the session-address preset decrypts the same frame with the mac stripped`() {
        val stripped = serviceData.substring(0, 10) + serviceData.substring(22)
        val scheme = Presets.xiaomiMiBeaconV4V5NoMac.template.copy(keyHex = bindkey)
        val result = CipherEngine.decrypt(
            scheme,
            stripped.hexToBytes(),
            FrameContext(address = address),
        )
        assertEquals("0FC4E044EF548D0A17000000", result.nonceHex)
        assertEquals(plaintext, result.plaintextHex)
        assertEquals(true, result.verified)
    }

    @Test
    fun `a wrong bindkey is reported as a tag failure, not as plaintext`() {
        val scheme = Presets.xiaomiMiBeaconV4V5.template.copy(keyHex = "00" + bindkey.substring(2))
        val result = CipherEngine.decrypt(scheme, serviceData.hexToBytes(), FrameContext())
        assertNull(result.plaintextHex)
        assertEquals(false, result.verified)
    }

    @Test
    fun `the preset claims the frame and reaches the plaintext through a session`() {
        val event = BleEvent(
            id = "advert",
            timestampEpochMicros = 1_000,
            direction = EventDirection.DEVICE_TO_PHONE,
            source = EventSource.HCI_SNOOP,
            operation = AttOperation.NOTIFICATION,
            payloadHex = serviceData,
        )
        val scheme = Presets.xiaomiMiBeaconV4V5.template.copy(keyHex = bindkey)
        val session = CaptureSession(
            name = "Mijia sensor",
            device = DeviceIdentity(address = address),
            events = listOf(event),
            ciphers = listOf(scheme),
        )
        val cache = DecryptCache(session, session.ciphers, session.events)
        assertFalse(cache.empty)
        assertEquals(plaintext, cache.payloadFor(event))
        assertEquals(1, cache.matchCountOf(scheme.id))
        assertEquals(true, cache.frameFor(event)!!.result.verified)
        assertEquals("Xiaomi MiBeacon v4/v5", cache.frameFor(event)!!.schemeName)
    }

    /** A frame too short to hold header, counter and MIC must not be claimed at all. */
    @Test
    fun `a short frame is not claimed`() {
        val scheme = Presets.xiaomiMiBeaconV4V5.template.copy(keyHex = bindkey)
        assertFalse(CipherEngine.matches(scheme, "58598D0A170FC4E044EF54".hexToBytes(), FrameContext()))
    }

    @Test
    fun `every shipped preset carries a source and survives being instantiated`() {
        assertTrue(Presets.all.isNotEmpty())
        for (preset in Presets.all) {
            assertTrue(preset.id, preset.source.isNotBlank())
            assertTrue(preset.id, preset.template.notes.isNotBlank())
            assertEquals(preset.id, preset.id, preset.template.presetId)
            assertEquals(preset.id, preset, Presets.byId(preset.id))
            assertTrue("${preset.id} ships a key", preset.template.keyHex.isEmpty())
            // An unproven layout has to say so where the operator will read it.
            if (!preset.verified) {
                assertTrue("${preset.id} is unverified but not marked", "EXPERIMENTAL" in preset.template.notes)
            }
        }
    }
}
